// <auto-generated />
using mchne_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace mchne_api.Migrations
{
    [DbContext(typeof(MchneContext))]
    [Migration("20180510030441_novels")]
    partial class novels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("mchne_api.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChapterNumber");

                    b.Property<string>("ContentUrl");

                    b.Property<int>("NovelID");

                    b.HasKey("ChapterID");

                    b.HasIndex("NovelID");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("mchne_api.Models.Novel", b =>
                {
                    b.Property<int>("NovelID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoverImage");

                    b.Property<string>("Title");

                    b.HasKey("NovelID");

                    b.ToTable("Novel");
                });

            modelBuilder.Entity("mchne_api.Models.Chapter", b =>
                {
                    b.HasOne("mchne_api.Models.Novel", "Novel")
                        .WithMany()
                        .HasForeignKey("NovelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
